# Auto-generated by gen_composite_code()
# 2026-03-04 18:13:12.509788
data |>

    mutate(pet = as.numeric(SPEI::thornthwaite(temp, lat[1]))) |>

  # [block-calc-ratio]
    mutate(.proxy_ratio = .proxy_prcp / .proxy_pet) |>
  # [/block-calc-ratio]

    mutate(prcp_3 = slider::slide_dbl(prcp, sum, .before = 2, .complete = TRUE)) |>

  # [block-log-transform]
  # [block-log-transform]
    mutate(.proxy_y = log10(.proxy_agg)) |>
  # [/block-log-transform]
  # [/block-log-transform]

  # [block-zscore]
  # [block-zscore]
    mutate(.proxy_index = (.proxy_y - mean(.proxy_y, na.rm = TRUE)) / sd(.proxy_y, na.rm = TRUE))
  # [/block-zscore]
  # [/block-zscore]
