# Auto-generated by gen_composite_code()
# 2026-03-05 13:43:34.513191

# Standardized Precipitation-Evapotranspiration Index (SPEI-3)
# Schema-Mapped Chained Version

library(SPEI)
library(lmom)
library(dplyr)
library(tidyr)
library(ggplot2)
library(slider)
library(lubridate)
# ==============================================================================
# 1. INPUT DATA
data(wichita)
climate_df <- data.frame(
  date = seq.Date(as.Date("1980-01-01"), by = "month", length.out = nrow(wichita)),
  prcp = wichita$PRCP,
  temp = wichita$TMED,
  lat  = 37.7
)
# 2. HELPER FUNCTIONS
calc_spei_probs <- function(x) {
  x_valid <- x[!is.na(x)]
  
  if (length(x_valid) < 4) return(rep(NA_real_, length(x))) 
  lmoms <- lmom::samlmu(x_valid)
  params <- lmom::pelglo(lmoms)
  probs <- rep(NA_real_, length(x))
  probs[!is.na(x)] <- lmom::cdfglo(x[!is.na(x)], params)
  pmax(pmin(probs, 0.999999), 0.000001)
}
# 3. SCHEMA-MAPPED PIPELINE (Chained)
results <- climate_df |> 
  arrange(date) |>
  # [block-calc-pet]
    mutate(pet = as.numeric(SPEI::thornthwaite(temp, lat[1]))) |>
  # [/block-calc-pet]

  # [block-calc-ratio]
    mutate(.proxy_ratio = prcp / pet) |>
  # [/block-calc-ratio]

  # [block-temporal-agg]
    mutate(.proxy_agg = slider::slide_dbl(.proxy_ratio, sum, .before = 2, .complete = TRUE)) |>
  # [/block-temporal-agg]

  # [block-log-transform]
    ## block-log-transform: take log10 of aggregated series - apply log10 transformation - to normalize the heavily skewed ratio distribution (Inputs: .proxy_agg) (Outputs: .proxy_y)
    mutate(.proxy_y = log10(.proxy_agg)) |>
  # [/block-log-transform]

  # [block-zscore]
    ## block-zscore: rescale to standard normal - calculate z-score (y - mean / sd) - final step to obtain the standardized RDI index (Inputs: .proxy_y) (Outputs: .proxy_index)
    mutate(.proxy_index = (.proxy_y - mean(.proxy_y, na.rm = TRUE)) / sd(.proxy_y, na.rm = TRUE))
  # [/block-zscore]
