# Auto-generated by gen_composite_code()
# 2026-03-06 09:53:13.6012

# Standardized Precipitation-Evapotranspiration Index (SPEI-3)
# Schema-Mapped Chained Version

library(SPEI)
library(lmom)
library(dplyr)
library(tidyr)
library(ggplot2)
library(slider)
library(lubridate)
# ==============================================================================
# 1. INPUT DATA
data(wichita)
climate_df <- data.frame(
  date = seq.Date(as.Date("1980-01-01"), by = "month", length.out = nrow(wichita)),
  prcp = wichita$PRCP,
  temp = wichita$TMED,
  lat  = 37.7
)
# 2. HELPER FUNCTIONS
calc_spei_probs <- function(x) {
  x_valid <- x[!is.na(x)]
  
  if (length(x_valid) < 4) return(rep(NA_real_, length(x))) 
  lmoms <- lmom::samlmu(x_valid)
  params <- lmom::pelglo(lmoms)
  probs <- rep(NA_real_, length(x))
  probs[!is.na(x)] <- lmom::cdfglo(x[!is.na(x)], params)
  pmax(pmin(probs, 0.999999), 0.000001)
}
# 3. SCHEMA-MAPPED PIPELINE (Chained)
results <- climate_df |> 
  arrange(date) |>
  # Calculate Potential Evapotranspiration (PET)
  mutate(pet = as.numeric(SPEI::thornthwaite(temp, lat[1]))) |>
  # Calculate water balance (precipitation - PET)
  mutate(balance = prcp - pet) |>
  # Calculate 3-month running sum of the water balance
  mutate(balance_3m = slider::slide_dbl(balance, sum, .before = 2, .complete = TRUE)) |>
  # Add month column for grouping
  mutate(month = month(date)) |>
  # Group by month to calculate probabilities for each month's distribution
  group_by(month) |>
  # Calculate the cumulative probability of the 3-month balance using GLO distribution
  mutate(spei_prob = calc_spei_probs(balance_3m)) |>
  ungroup() |>
  # Convert probabilities to Z-scores (the final SPEI value)
  mutate(spei_3 = qnorm(spei_prob))
