# Auto-generated by gen_composite_code()
# 2026-03-05 13:43:34.513191

# Standardized Precipitation-Evapotranspiration Index (SPEI-3)
# Schema-Mapped Chained Version

library(SPEI)
library(lmom)
library(dplyr)
library(tidyr)
library(ggplot2)
library(slider)
library(lubridate)
# ==============================================================================
# 1. INPUT DATA
data(wichita)
climate_df <- data.frame(
  date = seq.Date(as.Date("1980-01-01"), by = "month", length.out = nrow(wichita)),
  prcp = wichita$PRCP,
  temp = wichita$TMED,
  lat  = 37.7
)
# 2. HELPER FUNCTIONS
calc_spei_probs <- function(x) {
  x_valid <- x[!is.na(x)]
  
  if (length(x_valid) < 4) return(rep(NA_real_, length(x))) 
  lmoms <- lmom::samlmu(x_valid)
  params <- lmom::pelglo(lmoms)
  probs <- rep(NA_real_, length(x))
  probs[!is.na(x)] <- lmom::cdfglo(x[!is.na(x)], params)
  pmax(pmin(probs, 0.999999), 0.000001)
}
# 3. SCHEMA-MAPPED PIPELINE (Chained)
results <- climate_df |> 
  arrange(date) |>
# Standardized Precipitation Index (SPI-3)
library(SPEI)      # Just for the sample dataset
library(lmom)      # For L-moments and Gamma distribution
  prcp = wichita$PRCP
calc_spi_probs <- function(x) {
  # Guardrail: Need enough total data points
  # Calculate the probability of zero precipitation (q)
  n_zero <- sum(x_valid == 0)
  q <- n_zero / length(x_valid)
  x_nonzero <- x_valid[x_valid > 0]
  # Guardrail: Need enough non-zero points to calculate L-moments
  if (length(x_nonzero) < 3) return(rep(NA_real_, length(x)))
  # Fit the Gamma distribution
  lmoms <- lmom::samlmu(x_nonzero)
  params <- lmom::pelgam(lmoms)
  # Vectorized probability calculation
  is_zero <- !is.na(x) & (x == 0)
  is_nonzero <- !is.na(x) & (x > 0)
  probs[is_zero] <- q
  probs[is_nonzero] <- q + (1 - q) * lmom::cdfgam(x[is_nonzero], params)
  # Clamp probabilities to avoid -Inf/Inf Z-scores in the next step

data |>

  # [block-calc-pet]
    mutate(pet = as.numeric(SPEI::thornthwaite(temp, lat[1]))) |>
  # [/block-calc-pet]

  # [block-calc-ratio]
    mutate(.proxy_ratio = .proxy_prcp / .proxy_pet) |>
  # [/block-calc-ratio]

  # [block-temporal-agg]
    mutate(prcp_3 = slider::slide_dbl(prcp, sum, .before = 2, .complete = TRUE)) |>
  # [/block-temporal-agg]

  # [block-log-transform]
    ## block-log-transform: take log10 of aggregated series - apply log10 transformation - to normalize the heavily skewed ratio distribution (Inputs: .proxy_agg) (Outputs: .proxy_y)
    mutate(.proxy_y = log10(.proxy_agg)) |>
  # [/block-log-transform]

  # [block-zscore]
    ## block-zscore: rescale to standard normal - calculate z-score (y - mean / sd) - final step to obtain the standardized RDI index (Inputs: .proxy_y) (Outputs: .proxy_index)
    mutate(.proxy_index = (.proxy_y - mean(.proxy_y, na.rm = TRUE)) / sd(.proxy_y, na.rm = TRUE)) |>
  # [/block-zscore]
