# Schema composition -----------------------------------------------------
#
# A step can be pulled from one schema into another with import_step(), which
# tags the imported step with a `source_schema` provenance key. That key is
# what lets gen_composite_code() lift the step's existing, already-validated
# implementation out of a previously written script instead of asking an LLM
# to regenerate it.
#
# None of this is exported, and `source_schema` is deliberately absent from
# the user-facing schema surface. The provenance key is a deparsed R variable
# name, resolved out-of-band through gen_composite_code()'s `base_scripts`
# argument, so it does not survive being written to a file in any form a
# reader could follow. See vignette("future-extensions") for the
# locator-based redesign that would have to land before this becomes part of
# the public API.

#' Import a step from a source schema into the current schema
#'
#' @param schema The current schema being built.
#' @param source_schema The schema to import the step from.
#' @param id The id of the step to import.
#' @param source_schema_name Optional. A string to use as the provenance
#'   key, matched against `base_scripts` in `gen_composite_code()`.
#'   Defaults to the deparsed name of `source_schema`.
#' @param ... Optional field overrides (e.g. `inputs = c(".new_var")`).
#' @return The updated schema with the imported step appended.
#' @noRd
import_step <- function(schema, source_schema, id,
                        source_schema_name = NULL, ...) {
  to_import <- source_schema |>
    dplyr::filter(id == !!id)

  if (nrow(to_import) == 0) {
    stop(sprintf("Could not find step with id '%s' in the source schema.", id))
  }
  if (nrow(to_import) > 1) {
    warning(sprintf("Multiple steps found with id '%s'. Using the first.", id))
    to_import <- to_import |> dplyr::slice(1)
  }

  # Provenance: use explicit name if provided, otherwise deparse the argument
  to_import$source_schema <- source_schema_name %||%
    deparse(substitute(source_schema))

  new_args <- list(...)
  for (arg_name in names(new_args)) {
    if (is.list(to_import[[arg_name]])) {
      to_import[[arg_name]] <- list(new_args[[arg_name]])
    } else {
      to_import[[arg_name]] <- new_args[[arg_name]]
    }
  }

  # Preserve attributes before rbind (bind_rows drops the schema class)
  schema_name <- attr(schema, "name", exact = TRUE)
  schema_data <- attr(schema, "data", exact = TRUE)

  if (nrow(schema) == 0) {
    schema <- to_import
  } else {
    schema <- dplyr::bind_rows(schema, to_import)
  }

  class(schema) <- c("schema", "tbl_df", "tbl", "data.frame")
  attr(schema, "name") <- schema_name
  if (!is.null(schema_data)) {
    attr(schema, "data") <- schema_data
  }

  schema
}

#' Generate R code from a composite schema built from several sources
#'
#' Imported steps have their implementation lifted verbatim from the
#' corresponding base script; steps authored directly are generated by an
#' LLM using the preamble and prior chunks as style context.
#'
#' @param schema A schema assembled via import_step() and add_step().
#' @param base_scripts Named list mapping provenance keys to base scripts.
#' @param output_file Path to write the generated R script.
#' @param model The LLM used for the non-imported steps.
#' @return Invisibly, the generated code as a character string.
#' @noRd
gen_composite_code <- function(schema, base_scripts, output_file,
                               model = "anthropic/claude-opus-4-5") {
  # Create the chat client up front, before any file work, so an unsupported
  # `model` string fails fast rather than partway through the loop.
  chat <- ellmer::chat(model)

  code_chunks <- vector("list", nrow(schema))

  # Collect preambles from all base scripts once
  preambles <- paste(
    Filter(nchar, vapply(base_scripts, extract_preamble, character(1))),
    collapse = "\n\n"
  )

  preamble_lines <- unlist(strsplit(preambles, "\n"))
  preambles <- paste(unique(preamble_lines), collapse = "\n")

  for (i in seq_len(nrow(schema))) {
    id <- schema$id[i]

    # source_schema is set by import_step(); absent for add_step() nodes
    source_nm <- schema$source_schema[i]

    if (!is.null(source_nm) && !is.na(source_nm) && nchar(source_nm) > 0) {
      # -- Imported step: extract chunk from base script ----------------------
      script_path <- base_scripts[[source_nm]]

      if (is.null(script_path)) {
        cli::cli_abort(c(
          "Step {.val {id}} was imported from {.val {source_nm}}",
          "x" = "No matching entry found in {.arg base_scripts}."
        ))
      }

      code_chunks[[i]] <- extract_tagged_chunk(script_path, id)
    } else {
      prior_chunks <- paste(
        unlist(Filter(Negate(is.null), code_chunks[seq_len(i - 1)])),
        collapse = "\n\n"
      )
      style_context <- paste(
        Filter(nchar, c(preambles, prior_chunks)),
        collapse = "\n\n"
      )
      # Create a node-like object for the LLM function
      node <- list(
        id = schema$id[i],
        objective = schema$objective[i],
        decision = schema$decision[i],
        rationale = schema$rationale[i],
        inputs = schema$inputs[[i]],
        outputs = schema$outputs[[i]]
      )
      code_chunks[[i]] <- llm_generate_step(node, style_context, chat = chat)
    }
  }

  all_outputs <- unlist(schema$outputs)

  header <- sprintf(
    "# Auto-generated by gen_composite_code()\n# %s\n\n", Sys.time()
  )

  body_chunks <- paste(
    mapply(function(chunk, id) {
      code <- paste0("  ", gsub("\n", "\n  ", chunk))
      sprintf("  # [%s]\n%s\n  # [/%s]", id, code, id)
    }, code_chunks, schema$id),
    collapse = "\n\n"
  )
  body_chunks <- sub("\\s*\\|>\\s*$", "", body_chunks)

  full_code <- paste0(header, preambles, "\n\n", "data |>\n\n", body_chunks)

  writeLines(full_code, output_file)
  cli::cli_inform("Script written to: {.path {output_file}}")

  invisible(full_code)
}

# Extract chunk between # [id] and # [/id] markers --------------------------
extract_tagged_chunk <- function(script_path, id) {
  lines <- readLines(script_path)
  start <- which(trimws(lines) == sprintf("# [%s]", id))
  end <- which(trimws(lines) == sprintf("# [/%s]", id))

  if (length(start) == 0 || length(end) == 0) {
    cli::cli_abort(
      "Could not find id markers for {.val {id}} in {.path {script_path}}"
    )
  }

  paste(lines[(start + 1):(end - 1)], collapse = "\n")
}

# Extract lines before the first id marker -----------------------------------
extract_preamble <- function(script_path) {
  lines <- readLines(script_path)
  first_id <- which(grepl("^\\s*# \\[", lines))[1]
  if (is.na(first_id) || first_id <= 1) {
    return("")
  }
  paste(lines[seq_len(first_id - 1)], collapse = "\n")
}

# LLM code generation for new steps ------------------------------------------
llm_generate_step <- function(node, style_context, chat) {
  prompt <- glue::glue(
    "You are writing a step in an R analysis script.

    The existing code style is:
    ```r
    {style_context}
    ```

    Write R code for the following step. Reference the style above:
    - ID: {node$id}
    - Objective: {node$objective}
    - Decision: {node$decision}
    - Rationale: {node$rationale}
    - Inputs: {paste(unlist(node$inputs), collapse = ', ')}
    - Outputs: {paste(unlist(node$outputs), collapse = ', ')}

    Return only the R code, no explanation, no markdown fences."
  )

  response <- chat$chat(prompt)

  response
}

# Composite example schemas, used to exercise the composition path -------

#' @noRd
example_spei <- function() {
  build_schema() |>
    add_step(
      id = "step-calc-pet",
      objective = "transform average temperature to obtain potential evapotranspiration (PET)",
      decision = "use Thornthwaite equation",
      rationale = "estimates PET using only mean temperature and latitude",
      inputs = c(".proxy_tavg"),
      outputs = c(".proxy_pet")
    ) |>
    add_step(
      id = "step-calc-diff",
      objective = "calculate difference series between precipitation and PET",
      decision = "subtract PET from Precipitation (P - PET)",
      rationale = "represents the climatic water balance (surplus or deficit)",
      inputs = c(".proxy_prcp", ".proxy_pet"),
      outputs = c(".proxy_diff")
    ) |>
    add_step(
      id = "step-temporal-agg",
      objective = "perform temporal aggregation on the difference series",
      decision = "calculate rolling sum of the P-PET difference",
      rationale = "accumulates water balance over a specific time scale",
      inputs = c(".proxy_diff"),
      outputs = c(".proxy_agg")
    ) |>
    add_step(
      id = "step-dist-fit",
      objective = "fit a probability distribution to the aggregated series",
      decision = "fit a Log-Logistic distribution",
      rationale = "difference series can be negative, so Gamma cannot be used; Log-Logistic handles negative values",
      inputs = c(".proxy_agg"),
      outputs = c(".proxy_fit")
    ) |>
    add_step(
      id = "step-normalize",
      objective = "normalize the fitted values",
      decision = "transform to standard normal z-scores",
      rationale = "standardizes the index",
      inputs = c(".proxy_fit"),
      outputs = c(".proxy_index")
    )
}

#' @noRd
example_spi <- function() {
  build_schema() |>
    add_step(
      id = "step-temporal-agg",
      objective = "perform temporal aggregation on the input precipitation series",
      decision = "calculate rolling sum over user-defined time scale",
      rationale = "droughts operate on varying time scales (e.g., 3-month, 6-month)",
      inputs = c(".proxy_prcp"),
      outputs = c(".proxy_agg")
    ) |>
    add_step(
      id = "step-dist-fit",
      objective = "fit a probability distribution to the aggregated series",
      decision = "fit a Gamma distribution",
      rationale = "precipitation is zero-bounded and highly skewed; Gamma fits well",
      inputs = c(".proxy_agg"),
      outputs = c(".proxy_fit")
    ) |>
    add_step(
      id = "step-normalize",
      objective = "normalize the fitted values",
      decision = "transform the cumulative probabilities to standard normal z-scores",
      rationale = "allows comparison of SPI values across different climates",
      inputs = c(".proxy_fit"),
      outputs = c(".proxy_index")
    )
}

#' @noRd
example_rdi <- function() {
  spi_template <- example_spi()
  spei_template <- example_spei()

  build_schema() |>
    import_step(
      source_schema = spei_template,
      source_schema_name = "spei_template",
      id = "step-calc-pet"
    ) |>
    add_step(
      id = "step-calc-ratio",
      objective = "calculate the ratio of precipitation to PET",
      decision = "divide precipitation by PET",
      rationale = "RDI relies on the P/PET ratio rather than difference",
      inputs = c(".proxy_prcp", ".proxy_pet"),
      outputs = c(".proxy_ratio")
    ) |>
    import_step(
      source_schema = spi_template,
      source_schema_name = "spi_template",
      id = "step-temporal-agg",
      inputs = c(".proxy_ratio")
    ) |>
    add_step(
      id = "step-log-transform",
      objective = "take log10 of aggregated series",
      decision = "apply log10 transformation",
      rationale = "to normalize the heavily skewed ratio distribution",
      inputs = c(".proxy_agg"),
      outputs = c(".proxy_y")
    ) |>
    add_step(
      id = "step-zscore",
      objective = "rescale to standard normal",
      decision = "calculate z-score (y - mean / sd)",
      rationale = "final step to obtain the standardized RDI index",
      inputs = c(".proxy_y"),
      outputs = c(".proxy_index")
    )
}
