#' Generate analytical alternatives via LLM
#'
#' @description
#' `gen_alternatives()` takes an existing `schema` or `multiverse` and asks a
#' Large Language Model to suggest methodologically valid, alternative approaches for
#' a specific step (block) in your analysis pipeline.
#'
#' `prompt_alternatives()` is a helper function that constructs the exact instruction
#' set sent to the LLM.
#'
#' @details
#' **Important:** This function relies on the `ellmer` package to communicate with
#' Google's Gemini API. You must have your API credentials configured correctly in
#' your R environment (e.g., via the `GEMINI_API_KEY` environment variable) for
#' this to work.
#'
#' @param x A `schema` or `multiverse` object, or a character string specifying
#'   the file path to a valid `tines` YAML file.
#' @param block A character string. The exact `tag` of the step/node you want
#'   the LLM to generate alternatives for.
#' @param n An integer. The number of distinct alternatives you want the LLM
#'   to generate. Defaults to `3`.
#' @param provider A character string specifying the LLM provider. Currently
#'   defaults to `"gemini"`. (`gemini-3-flash-preview` via `ellmer`).
#' @param file_path A character string specifying where to save the generated
#'   YAML output. If `NULL` (the default), `capture.output()` will return the
#'   result as a character vector.
#' @param print A logical. If `TRUE`, the prompt generated by `prompt_alternatives()` will be printed to the console in a readable format. Default to `FALSE`
#' @param ... Additional arguments passed to methods or to `ellmer::chat_google_gemini()`.
#'
#' @return
#' * `gen_alternatives()` invisibly returns `NULL` and writes the output to `file_path`.
#' * `prompt_alternatives()` returns a formatted character string containing the LLM prompt.
#'
#' @export
#' @rdname gen_alternatives
#'
#' @examples
#' \dontrun{
#' # Generate 3 alternatives for the "handle-missing-data" step
#' gen_alternatives(
#'   x = my_schema,
#'   block = "handle-missing-data",
#'   n = 3,
#'   file_path = "alternatives.yaml"
#' )
#' }
gen_alternatives <- function(x, block, n = 3,
                             provider = "gemini", file_path = NULL, ...){
  UseMethod("gen_alternatives")
}

#' @export
#' @rdname gen_alternatives
gen_alternatives.schema <- function(x, block, n = 3,
                             provider = "gemini", file_path = NULL, ...){

  # allow both a yaml file or a tine (schema/ multiverse) object
  if (file.exists(x)) tine_str <- readLines(x) else tine_str <- write_tines(x)
  temp_file_path <- tempfile(tmpdir = tempdir(), fileext = "yaml")
  writeLines(tine_str, temp_file_path)
  tine_file <- ellmer::google_upload(temp_file_path)

  prompt <- prompt_alternatives(block = block, n = n)

  chat <- ellmer::chat_google_gemini(model = "gemini-3-flash-preview")
  utils::capture.output(chat$chat(prompt, tine_file), file = file_path)
  invisible()
}


#' @export
#' @rdname gen_alternatives
gen_alternatives.multiverse <- function(x, block, ...){
  valid_schema <- NULL

  # find the first schema in the multiverse that contains the target block
  for (schema in x) {
    tags <- purrr::map_chr(schema$nodes, "tag")
    if (block %in% tags) {
      valid_schema <- schema
      break
    }
  }

  if (is.null(valid_schema)) {
    cli::cli_abort(
      "Target block {.val {block}} not found in any branch of this multiverse."
    )
  }

  gen_alternatives(valid_schema, block, ...)

}


#' @export
#' @rdname gen_alternatives
prompt_alternatives <- function(block, n = 3, print = FALSE){
  res <- cli::format_inline(
    '### Role
You are an expert Data Analyst and Methodologist. You are reviewing an analysis schema to identify "Forking Paths" -- alternative analytical choices that are equally valid but distinct from the current approach.

### Definitions
The schema provided to you consists of blocks with:
- **ACTION**: The goal of the block (What needs to be done).
- **DECISION**: The specific implementation chosen (How it is done).
- **JUSTIFICATION**: The reasoning behind that decision.
- **TAG**: The unique identifier for the block (kebab-case).

### Task
Focus specifically on the block tagged: "{block}".
Your goal is to generate {n} distinct, valid alternatives for this block.

For each alternative:
1.  **Keep the same ACTION** (the goal remains constant).
2.  **Change the DECISION** to a different but methodologically sound approach.
3.  **Provide a new JUSTIFICATION** explaining why this alternative is valid.
4.  **Create a new TAG** that reflects the new decision (must be kebab-case).

### Output Format
Please output the result in **strictly valid YAML format**.

**Crucial Formatting Rules:**
1.  Include a `meta` section at the top with `type: alternative` and the `target_block`.
2.  Output strictly valid YAML.
Formatting Rule: All text values (decision, justification) must be enclosed in double quotes ("). Do not use block styles (| or >). Do not wrap lines or insert \n characters within the quotes; keep the text as a single continuous string."
3.  Do not include markdown code fences (like ```yaml) or conversational text. Just the raw YAML.

### Example Output Structure
meta:
  type: tines_alternative
  block: {block}
alternatives:
  - tag: block-new-method-name
    action: Repeat the original action
    decision: Description of the new decision...
    justification: |
      This is the first line of the reasoning.
      This is the second line, making it easy to read.
  - tag: block-another-method
    ...'
  )

  if (print) cat(res) else res

}



#' Expand a schema with an alternative YAML into a multiverse
#'
#' @param x A `schema` object.
#' @param alternatives an `alternatives` object or the path to an alternative YAML
#' @param include_original A logical. If `TRUE`, the original schema will be included as a branch in the resulting multiverse. Defaults to `TRUE`.
#' @param ... Additional arguments.
#'
#' @rdname expand
#' @export
#' @examples
#'
#' # expand on a schema
#' base_schema <- example_football()
#' alts <- example_alternatives(case = "football")
#' expand_tines(base_schema, alts)
#'
#' # read the alternatives from a YAML file
#' tmp_file <- tempfile(fileext = ".yaml")
#' write_alternatives(alts, tmp_file)
#' expand_tines(base_schema, tmp_file)
#'
#' # expand on the multiverse
#' multiverse <- example_multiverse()
#' alts <- example_alternatives(case = "hdi")
#' expand_tines(multiverse, alts)
#'
expand_tines <- function(x, alternatives, ...) {
  UseMethod("expand_tines")
}

#' @rdname expand
#' @export
expand_tines.schema <- function(x, alternatives, include_original = TRUE, ...) {

  if (is.character(alternatives) && file.exists(alternatives)) {
    alts_data <- read_alternatives(alternatives)
  } else {
    alts_data <- alternatives
  }

  target <- attr(alts_data,"block")


  tags <- x$nodes$tag
  if (!target %in% tags) {
    cli::cli_abort("Target block {.val {target}} not found in the base schema.")
  }
  idx <- which(tags == target)


  new_schemas <- lapply(alts_data, function(alt) {
    branch <- x

    branch$nodes$tag[[idx]] <- alt$tag
    branch$nodes$decision[[idx]] <- alt$decision
    branch$nodes$justification[[idx]] <- alt$justification

    # Rewire the edges!
    branch$edges$from[branch$edges$from == target] <- alt$tag
    branch$edges$to[branch$edges$to == target] <- alt$tag
    return(branch)
  })
  names(new_schemas) <- vapply(alts_data, function(a) a$tag, character(1))


  if (include_original) new_schemas <- c(list(original = x), new_schemas)

  new_multiverse(new_schemas)


}

#' @rdname expand
#' @export
expand_tines.multiverse <- function(x, alternatives, ...) {

  if (is.character(alternatives) && file.exists(alternatives)) {
    alts_data <- read_alternatives(alternatives)
  } else {
    alts_data <- alternatives
  }
  target <- attr(alts_data,"block")

  expanded_list <- lapply(x, function(single_schema) {

    tags <- single_schema$nodes$tag

    if (target %in% tags) {
      # It has the block! Expand it, and extract the resulting list of schemas
      expanded_mini_multi <- expand_tines(single_schema, alternatives, include_original = FALSE)
      return(expanded_mini_multi)
    } else {
      # It DOES NOT have the block! Return it untouched, wrapped in a list
      # so it can be cleanly flattened with the others later.
      return(list(single_schema))
    }


  })
  all_schemas <- c(x, expanded_list)
  all_schemas

}
