#' Generate R code for a specific alternative branch
#'
#' @param base_schema The original schema object or file path.
#' @param base_code The file path to the original R script.
#' @param alternatives A single alternative object (list with tag, decision, etc.).
#' @param output The directory where the generated R script will be saved. Defaults to "scripts".
#' @param provider The LLM provider to use for code generation. Currently only "gemini".
#' @param print A logical. If `TRUE`, the prompt generated by `prompt_alternatives()` will be printed to the console in a readable format. Default to `FALSE`
#' @param has_base_code,has_alternative A logical. If `TRUE`, the prompt will include instructions to
#' rewrite an existing base code or implement a specific alternative. Default to `FALSE`.
#' @param data Optional. Either a file path to a data file (e.g., CSV) or a
#'   string like `"packagename::dataset"` indicating a built-in package dataset.
#'   If `NULL`, the LLM will not receive any data instructions.
#' @export
#' @rdname gen_code
#' @examples
#' \dontrun{
#' hdi <- example_schema()
#' gen_code(hdi,
#'          base_code = system.file("hdi.R", package = "tines"),
#'          alternative = system.file("hdi-alt.yaml", package = "tines"),
#'          output = here::here("inst/"))
#' }
#'
gen_code <- function(base_schema, base_code = NULL, alternatives = NULL,
                     data = NULL, output = "scripts", provider = "gemini") {

  # currently I provide the option of not providing alternatives and base code,
  # but I don't think they would work very well
  # TODO: fix bug - gen_code(here::here("draft_schema.yml")) - it doesn't convert the yaml into an R object
  is_file <- endsWith(output, ".R") || endsWith(output, ".r")

  if (is.null(alternatives)){

    if (is_file) {
      target_file <- output
      target_dir  <- dirname(output)
    } else {
      target_dir  <- output
      target_file <- file.path(output, "pipeline.R")
    }

    if (!dir.exists(output)) dir.create(target_dir, recursive = TRUE)
    cli::cli_alert_info("Generating script directly from schema")

    gen_code_single(
      base_schema = base_schema,
      base_code = NULL,
      alternative = NULL,
      data = data,
      file_path = target_file
    )

    cli::cli_alert_success("Script generated successfully at {.val {target_file}}!")
    return(invisible())
  }

  if (is_file) {
    cli::cli_abort(c(
      "x" = "Conflicting arguments.",
      "i" = "You provided {.arg alternatives}, which generates multiple files.",
      "!" = "{.arg output} must be a directory, not a specific file path like {.val {output}}."
    ))
  }

  if (!dir.exists(output)) dir.create(output, recursive = TRUE)

  alts <- read_alternatives(alternatives)
  block <- attr(alts, "block")

  for (i in seq_along(alts)) {
    # Extract the single alternative for this iteration
    alt <- alts[[i]]
    alt <- do.call(new_alternatives, list(alt, block = block))

    raw_tag <- if (is.null(alt[[1]]$tag) || is.na(alt[[1]]$tag) || alt[[1]]$tag == "") "unnamed" else alt[[1]]$tag
    safe_tag <- gsub("[^a-zA-Z0-9]+", "_", raw_tag)
    safe_tag <- gsub("^_|_$", "", safe_tag) # Trim hanging underscores

    # Build the clean path (e.g., "scripts/alt_01_mixed_effects.R")
    current_file_name <- file.path(output, sprintf("alt_%02d_%s.R", i, safe_tag))

    cli::cli_alert_info("Generating code for alternative {i}/{length(alts)}: {.val {raw_tag}}")

    # 4. Call the single generation function
    gen_code_single(
      base_schema = base_schema,
      base_code = base_code,
      alternative = alt,
      data = data,
      file_path = current_file_name
    )
  }

  cli::cli_alert_success("All {length(alts)} scripts generated successfully!")
}

#' @keywords internal
gen_code_single <- function(base_schema, base_code = NULL, alternative = NULL,
                            data = NULL, provider = "gemini", file_path = NULL) {
  if (is.null(file_path)) {
    cli::cli_abort("You must provide a {.arg file_path} to save the generated code.")
  }

  has_code <- !is.null(base_code)
  has_alt  <- !is.null(alternative)
  has_data <- !is.null(data)

  base_prompt <- prompt_code(has_base_code = has_code, has_alternative = has_alt,
                             has_data = has_data)
  txt_input <- format_llm_context(base_schema, base_code, alternative, data)

  full_prompt <- paste0(
    base_prompt,
    "\n\n=== CURRENT SCHEMA ===\n",
    txt_input
  )

  chat <- ellmer::chat_google_gemini(model = "gemini-2.5-flash")
  utils::capture.output(chat$chat(full_prompt), file = file_path)


  invisible()
}


#' @keywords internal
format_llm_context <- function(base_schema, base_code = NULL, alternative = NULL,
                               data = NULL) {
  txt_input <- paste0("=== SCHEMA ===\n", yaml::as.yaml(base_schema), "\n")

  if (!is.null(data)) {
    is_pkg_data <- grepl("::", data, fixed = TRUE)
    if (is_pkg_data) {
      data_txt <- paste0(
        "The data is available as a built-in package dataset: `", data, "`. ",
        "Load it with `data(", sub(".*::", "", data), ", package = \"",
        sub("::.*", "", data), "\")` or reference it directly."
      )
    } else {
      data_txt <- paste0(
        "The data should be imported from the file: `", data, "`. ",
        "Use `readr::read_csv(\"", data, "\")` (or the appropriate reader) to load it."
      )
    }
    txt_input <- paste0(txt_input, "\n=== DATA ===\n", data_txt, "\n")
  }

  if (!is.null(base_code)) {
    if (!file.exists(base_code)) {
      cli::cli_abort("Base code file not found: {.val {base_code}}")
    }
    base_code_txt <- paste(readLines(base_code), collapse = "\n")
    txt_input <- paste0(txt_input, "\n=== BASE R CODE ===\n", base_code_txt, "\n")
  }

  if (!is.null(alternative)) {
    alt_txt <- yaml::as.yaml(alternative)
    txt_input <- paste0(txt_input, "\n=== ALTERNATIVE TO IMPLEMENT ===\n", alt_txt, "\n")
  }

  return(txt_input)
}

#' @export
#' @rdname gen_code
prompt_gen_code <- function(has_base_code = FALSE, has_alternative = FALSE,
                        has_data = FALSE, print = FALSE) {
  data_instruction <- if (has_data) {
    paste0(
      "A DATA section is provided. This is the entry point for the entire pipeline — ",
      "start the script by loading this data. ",
      "Do NOT generate, simulate, or create any dummy or synthetic data under any circumstances."
    )
  } else {
    "No data file is specified - if data loading is required, use a sensible placeholder or note it in a comment. "
  }

  if (has_base_code && has_alternative) {
    # The Multiverse Prompt
    prompt <- cli::format_inline(
      "You are an expert R programmer assisting a data analyst with a multiverse analysis. ",
      "Attached is a text document containing three sections: SCHEMA, BASE R CODE, and ALTERNATIVE TO IMPLEMENT.\n\n",
      data_instruction,
      "Your task is to rewrite the BASE R CODE to implement the requested alternative. ",
      "Locate the code corresponding to the 'Block', and rewrite only that section using the new 'Decision'. ",
      "Keep all other data loading, processing, and reporting steps exactly the same. ",
      "Output ONLY the complete, updated R script. Do not start with markdown formatting blocks (like ```R) or backticks."
    )
  } else {
    # The From-Scratch Prompt
    prompt <- cli::format_inline(
      "You are an expert R programmer. ",
      "Attached is a text document containing a SCHEMA that defines a data processing pipeline.\n\n",
      data_instruction,
      "Your task is to write a complete, working R script from scratch that implements this pipeline step-by-step. ",
      "Use modern R practices (like dplyr or base pipe) and ensure variables flow correctly from one step to the next as defined by the inputs and outputs. ",
      "Output ONLY the complete R script. Do not start with markdown formatting blocks (like ```R) or backticks."
    )
  }

  if (print)
    cat(prompt)
  else
    prompt
}
