#' Generate R code for a specific alternative branch
#'
#' @param base_schema The original schema object or file path.
#' @param base_code The file path to the original R script.
#' @param alternatives A single alternative object (list with tag, decision, etc.).
#' @param output_dir The directory where the generated R script will be saved. Defaults to "scripts".
#' @param provider The LLM provider to use for code generation. Currently only "gemini".
#' @param print A logical. If `TRUE`, the prompt generated by `prompt_alternatives()` will be printed to the console in a readable format. Default to `FALSE`
#'
#' @export
#' @rdname gen_code
#' @examples
#' \dontrun{
#' hdi <- example_schema()
#' gen_code(hdi,
#'          base_code = system.file("hdi.R", package = "tines"),
#'          alternative = system.file("hdi-alt.yaml", package = "tines"),
#'          output_dir = here::here("inst/"))
#' }
#'
gen_code <- function(base_schema, base_code, alternatives,
                     output_dir = "scripts", provider = "gemini") {


  if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)

  alts <- read_alternatives(alternatives)
  block <- attr(alts, "block")

  for (i in seq_along(alts)) {
    # Extract the single alternative for this iteration
    alt <- alts[[i]]
    alt <- do.call(new_alternatives, list(alt, block = block))

    raw_tag <- if (is.null(alt[[1]]$tag) || is.na(alt[[1]]$tag) || alt[[1]]$tag == "") "unnamed" else alt[[1]]$tag
    safe_tag <- gsub("[^a-zA-Z0-9]+", "_", raw_tag)
    safe_tag <- gsub("^_|_$", "", safe_tag) # Trim hanging underscores

    # Build the clean path (e.g., "scripts/alt_01_mixed_effects.R")
    current_file_name <- file.path(output_dir, sprintf("alt_%02d_%s.R", i, safe_tag))

    cli::cli_alert_info("Generating code for alternative {i}/{length(alts)}: {.val {raw_tag}}")

    # 4. Call the single generation function
    gen_code_single(
      base_schema = base_schema,
      base_code = base_code,
      alternative = alt,
      file_path = current_file_name
    )
  }

  cli::cli_alert_success("All {length(alts)} scripts generated successfully!")
}

#' @keywords internal
gen_code_single <- function(base_schema, base_code, alternative,
                            provider = "gemini", file_path = NULL) {

  if (is.null(file_path)) {
    cli::cli_abort("You must provide a {.arg file_path} to save the generated code.")
  }

  base_prompt <- prompt_code()
  txt_input <- format_llm_context(base_schema, base_code, alternative)

  full_prompt <- paste0(
    base_prompt,
    "\n\n=== CURRENT SCHEMA ===\n",
    txt_input
  )

  chat <- ellmer::chat_google_gemini(model = "gemini-2.5-pro")
  utils::capture.output(chat$chat(full_prompt), file = file_path)


  invisible()
}


#' @keywords internal
format_llm_context <- function(base_schema, base_code, alternative) {

  base_schema_txt <- yaml::as.yaml(base_schema)

  if (!file.exists(base_code)) {
    cli::cli_abort("Base code file not found: {.val {base_code}}")
  }
  base_code_txt <- paste(readLines(base_code), collapse = "\n")

  alt_txt <- yaml::as.yaml(alternative)

  txt_input <- paste0(
    "=== BASE SCHEMA ===", base_schema_txt,
    "\n=== BASE R CODE ===", base_code_txt,
    "\n=== ALTERNATIVE TO IMPLEMENT ===", alt_txt
  )

  return(txt_input)
}

#' @export
#' @rdname gen_code
prompt_code <- function(print = FALSE) {

  prompt <- cli::format_inline(
    "You are an expert R programmer assisting a data analyst with a multiverse analysis. ",
    "Attached is a text document containing three sections:\n",
    "1. BASE SCHEMA: The pipeline outline.\n",
    "2. BASE R CODE: The working R script that executes the base schema.\n",
    "3. ALTERNATIVE TO IMPLEMENT: The specific modification to make to the pipeline.\n\n",
    "Your task is to rewrite the BASE R CODE to implement the requested alternative. ",
    "Locate the code corresponding to the 'Block', and rewrite only that section using the new 'Decision'. ",
    "Keep all other data loading, processing, and reporting steps exactly the same. ",
    "Output ONLY the complete, updated R script. Do not start with markdown formatting blocks (like ```R) or backticks."
  )

  if (print) cat(prompt) else prompt
}
