#' Generate analytical alternatives via LLM
#'
#' @description
#' `gen_alternatives()` takes an existing `schema` or `multiverse` and asks a
#' Large Language Model to suggest methodologically valid, alternative approaches for
#' a specific step (block) in your analysis pipeline.
#'
#' `prompt_alternatives()` is a helper function that constructs the exact instruction
#' set sent to the LLM.
#'
#' @details
#' **Important:** This function relies on the `ellmer` package to communicate with
#' Google's Gemini API. You must have your API credentials configured correctly in
#' your R environment (e.g., via the `GEMINI_API_KEY` environment variable) for
#' this to work.
#'
#' @param x A `schema` or `multiverse` object, or a character string specifying
#'   the file path to a valid `tines` YAML file.
#' @param block A character string. The exact `tag` of the step/node you want
#'   the LLM to generate alternatives for.
#' @param n An integer. The number of distinct alternatives you want the LLM
#'   to generate. Defaults to `3`.
#' @param provider A character string specifying the LLM provider. Currently
#'   defaults to `"gemini"`. (`gemini-3-flash-preview` via `ellmer`).
#' @param file_path A character string specifying where to save the generated
#'   YAML output. If `NULL` (the default), `capture.output()` will return the
#'   result as a character vector.
#' @param print A logical. If `TRUE`, the prompt generated by `prompt_alternatives()` will be printed to the console in a readable format. Default to `FALSE`
#'
#' @return
#' * `gen_alternatives()` invisibly returns `NULL` and writes the output to `file_path`.
#' * `prompt_alternatives()` returns a formatted character string containing the LLM prompt.
#'
#' @export
#' @rdname gen_alternatives
#'
#' @examples
#' \dontrun{
#' # Generate 3 alternatives for the "handle-missing-data" step
#' gen_alternatives(
#'   x = my_schema,
#'   block = "handle-missing-data",
#'   n = 3,
#'   file_path = "alternatives.yaml"
#' )
#' }
gen_alternatives <- function(x, block, n = 3,
                             provider = "gemini", file_path = NULL){

  # allow both a yaml file or a tine (schema/ multiverse) object
  if (file.exists(x)) tine_str <- readLines(x) else tine_str <- write_tines(x)
  temp_file_path <- tempfile(tmpdir = tempdir(), fileext = "yaml")
  writeLines(tine_str, temp_file_path)
  tine_file <- ellmer::google_upload(temp_file_path)

  prompt <- prompt_alternatives(block = block, n = n)

  chat <- ellmer::chat_google_gemini(model = "gemini-3-flash-preview")
  utils::capture.output(chat$chat(prompt, tine_file), file = file_path)
  invisible()
}

#' @export
#' @rdname gen_alternatives
prompt_alternatives <- function(block, n = 3, print = FALSE){
  res <- cli::format_inline(
    '### Role
You are an expert Data Analyst and Methodologist. You are reviewing an analysis schema to identify "Forking Paths" -- alternative analytical choices that are equally valid but distinct from the current approach.

### Definitions
The schema provided to you consists of blocks with:
- **ACTION**: The goal of the block (What needs to be done).
- **DECISION**: The specific implementation chosen (How it is done).
- **JUSTIFICATION**: The reasoning behind that decision.
- **TAG**: The unique identifier for the block (kebab-case).

### Task
Focus specifically on the block tagged: "{block}".
Your goal is to generate {n} distinct, valid alternatives for this block.

For each alternative:
1.  **Keep the same ACTION** (the goal remains constant).
2.  **Change the DECISION** to a different but methodologically sound approach.
3.  **Provide a new JUSTIFICATION** explaining why this alternative is valid.
4.  **Create a new TAG** that reflects the new decision (must be kebab-case).

### Output Format
Please output the result in **strictly valid YAML format**.

**Crucial Formatting Rules:**
1.  Include a `meta` section at the top with `type: vista_alternative` and the `target_block`.
2.  Output strictly valid YAML.
Formatting Rule: All text values (decision, justification) must be enclosed in double quotes ("). Do not use block styles (| or >). Do not wrap lines or insert \n characters within the quotes; keep the text as a single continuous string."
3.  Do not include markdown code fences (like ```yaml) or conversational text. Just the raw YAML.

### Example Output Structure
meta:
  type: tines_alternative
  block: {block}
alternatives:
  - tag: block-new-method-name
    action: Repeat the original action
    decision: Description of the new decision...
    justification: |
      This is the first line of the reasoning.
      This is the second line, making it easy to read.
  - tag: block-another-method
    ...'
  )

  if (print) cat(res) else res

}

