#' Generate R code from a composite schema assembled from multiple source schemas
#'
#' @param schema A schema object assembled via `build_schema()`, `import_block()`,
#'   and `add_block()`.
#' @param base_scripts Named list mapping source schema object names to their 
#'   base R scripts, e.g. `list(spei_template = here::here("inst/spei.R"))`.
#' @param output_file Path to write the generated R script.
#' @return Invisibly returns the generated code as a character string.
#' @export
#' @examples
#' \dontrun{
#' schema <- example_rdi()
#'
#' code <- gen_composite_code(
#'   schema       = schema,
#'   base_scripts = list(
#'     spei_template = here::here("inst/spei.R"),
#'     spi_template  = here::here("inst/spi.R")
#'   ),
#'   output_file  = here::here("inst/rdi.R")
#' )
#' }
gen_composite_code <- function(schema, base_scripts, output_file) {
  nodes <- schema$nodes
  edges <- schema$edges
  code_chunks <- vector("list", nrow(nodes))

  # Collect preambles from all base scripts once
  preambles <- paste(
    Filter(nchar, vapply(base_scripts, extract_preamble, character(1))),
    collapse = "\n\n"
  )

  preamble_lines <- unlist(strsplit(preambles, "\n"))
  preambles <- paste(unique(preamble_lines), collapse = "\n")

  for (i in seq_len(nrow(nodes))) {
    node <- nodes[i, ]
    tag  <- node$tag
    
    # source_schema is set by import_block(); absent for add_block() nodes
    source_nm <- if ("source_schema" %in% names(node)) node$source_schema else NA
    
    if (!is.null(source_nm) && !is.na(source_nm)) {
      # -- Imported block: extract chunk from base script ----------------------
      script_path <- base_scripts[[source_nm]]
      
      if (is.null(script_path)) {
        cli::cli_abort(c(
          "Block {.val {tag}} was imported from {.val {source_nm}}",
          "x" = "No matching entry found in {.arg base_scripts}."
        ))
      }
      
      code_chunks[[i]] <- extract_tagged_chunk(script_path, tag)
      
    } else {
       prior_chunks <- paste(
        unlist(Filter(Negate(is.null), code_chunks[seq_len(i - 1)])),
        collapse = "\n\n"
      )
      style_context <- paste(
        Filter(nchar, c(preambles, prior_chunks)),
        collapse = "\n\n"
      )
      code_chunks[[i]] <- llm_generate_block(node, style_context)
    }
  }
  
  all_outputs <- unlist(nodes$outputs)
  
  header <- sprintf(
    "# Auto-generated by gen_composite_code()\n# %s\n\n", Sys.time()
  )

 body_chunks <- paste(
    mapply(function(chunk, tag) {
      code <- paste0("  ", gsub("\n", "\n  ", chunk))
      sprintf("  # [%s]\n%s\n  # [/%s]", tag, code, tag)
    }, code_chunks, nodes$tag),
    collapse = "\n\n"
  )
  body_chunks <- sub("\\s*\\|>\\s*$", "", body_chunks)
  
  full_code <- paste0(header, preambles, "\n\n", "data |>\n\n", body_chunks)

  writeLines(full_code, output_file)
  cli::cli_inform("Script written to: {.path {output_file}}")
  
  invisible(full_code)
}

# Extract chunk between # [tag] and # [/tag] markers --------------------------
extract_tagged_chunk <- function(script_path, tag) {
  lines <- readLines(script_path)
  start <- which(trimws(lines) == sprintf("# [%s]", tag))
  end   <- which(trimws(lines) == sprintf("# [/%s]", tag))
  
  if (length(start) == 0 || length(end) == 0) {
    cli::cli_abort(
      "Could not find tag markers for {.val {tag}} in {.path {script_path}}"
    )
  }
  
  paste(lines[(start + 1):(end - 1)], collapse = "\n")
}

# Extract lines before the first tag marker -----------------------------------
extract_preamble <- function(script_path) {
  lines <- readLines(script_path)
  first_tag <- which(grepl("^\\s*# \\[", lines))[1]
  if (is.na(first_tag) || first_tag <= 1) return("")
  paste(lines[seq_len(first_tag - 1)], collapse = "\n")
}

# LLM code generation for new blocks ------------------------------------------
llm_generate_block <- function(node, style_context) {
  prompt <- glue::glue(
    "You are writing a step in an R analysis script.
    
    The existing code style is:
    ```r
    {style_context}
    ```
    
    Write R code for the following step. Reference the style above:
    - Tag: {node$tag}
    - Action: {node$action}
    - Decision: {node$decision}
    - Justification: {node$justification}
    - Inputs: {paste(unlist(node$inputs), collapse = ', ')}
    - Outputs: {paste(unlist(node$outputs), collapse = ', ')}
    
    Return only the R code, no explanation, no markdown fences."
  )
  
  chat <- ellmer::chat_google_gemini(model = "gemini-2.5-flash")
  response <- chat$chat(prompt)
  
  response
}
