#' Generate R code from a composite schema assembled from multiple source schemas
#'
#' @param schema A schema object assembled via `build_schema()`, `import_step()`,
#'   and `add_step()`.
#' @param base_scripts Named list mapping source schema object names to their 
#'   base R scripts, e.g. `list(spei_template = here::here("inst/spei.R"))`.
#' @param output_file Path to write the generated R script.
#' @param model The LLM to use for generating new (non-imported) steps, as a
#'   string in `"provider/model"` form (e.g. `"anthropic/claude-opus-4-5"`,
#'   `"openai/gpt-5"`, `"google_gemini/gemini-2.5-flash"`), passed to
#'   `ellmer::chat()`. See [ellmer::chat()] for the full list of supported
#'   providers. Defaults to `"anthropic/claude-opus-4-5"`.
#' @return Invisibly returns the generated code as a character string.
#' @export
#' @examples
#' \dontrun{
#' schema <- example_rdi()
#'
#' code <- gen_composite_code(
#'   schema       = schema,
#'   base_scripts = list(
#'     spei_template = here::here("inst/spei.R"),
#'     spi_template  = here::here("inst/spi.R")
#'   ),
#'   output_file  = here::here("inst/rdi.R")
#' )
#' }
gen_composite_code <- function(schema, base_scripts, output_file,
                               model = "anthropic/claude-opus-4-5") {
  # Create the chat client up front, before any file work, so an unsupported
  # `model` string fails fast rather than partway through the loop.
  chat <- ellmer::chat(model)

  code_chunks <- vector("list", nrow(schema))

  # Collect preambles from all base scripts once
  preambles <- paste(
    Filter(nchar, vapply(base_scripts, extract_preamble, character(1))),
    collapse = "\n\n"
  )

  preamble_lines <- unlist(strsplit(preambles, "\n"))
  preambles <- paste(unique(preamble_lines), collapse = "\n")

  for (i in seq_len(nrow(schema))) {
    id <- schema$id[i]
    
    # source_schema is set by import_step(); absent for add_step() nodes
    source_nm <- schema$source_schema[i]
    
    if (!is.null(source_nm) && !is.na(source_nm) && nchar(source_nm) > 0) {
      # -- Imported step: extract chunk from base script ----------------------
      script_path <- base_scripts[[source_nm]]
      
      if (is.null(script_path)) {
        cli::cli_abort(c(
          "Step {.val {id}} was imported from {.val {source_nm}}",
          "x" = "No matching entry found in {.arg base_scripts}."
        ))
      }
      
      code_chunks[[i]] <- extract_tagged_chunk(script_path, id)
      
    } else {
       prior_chunks <- paste(
        unlist(Filter(Negate(is.null), code_chunks[seq_len(i - 1)])),
        collapse = "\n\n"
      )
      style_context <- paste(
        Filter(nchar, c(preambles, prior_chunks)),
        collapse = "\n\n"
      )
      # Create a node-like object for the LLM function
      node <- list(
        id = schema$id[i],
        fork = schema$fork[i],
        path = schema$path[i],
        rationale = schema$rationale[i],
        inputs = schema$inputs[[i]],
        outputs = schema$outputs[[i]]
      )
      code_chunks[[i]] <- llm_generate_step(node, style_context, chat = chat)
    }
  }
  
  all_outputs <- unlist(schema$outputs)
  
  header <- sprintf(
    "# Auto-generated by gen_composite_code()\n# %s\n\n", Sys.time()
  )

 body_chunks <- paste(
    mapply(function(chunk, id) {
      code <- paste0("  ", gsub("\n", "\n  ", chunk))
      sprintf("  # [%s]\n%s\n  # [/%s]", id, code, id)
    }, code_chunks, schema$id),
    collapse = "\n\n"
  )
  body_chunks <- sub("\\s*\\|>\\s*$", "", body_chunks)
  
  full_code <- paste0(header, preambles, "\n\n", "data |>\n\n", body_chunks)

  writeLines(full_code, output_file)
  cli::cli_inform("Script written to: {.path {output_file}}")
  
  invisible(full_code)
}

# Extract chunk between # [id] and # [/id] markers --------------------------
extract_tagged_chunk <- function(script_path, id) {
  lines <- readLines(script_path)
  start <- which(trimws(lines) == sprintf("# [%s]", id))
  end   <- which(trimws(lines) == sprintf("# [/%s]", id))
  
  if (length(start) == 0 || length(end) == 0) {
    cli::cli_abort(
      "Could not find id markers for {.val {id}} in {.path {script_path}}"
    )
  }
  
  paste(lines[(start + 1):(end - 1)], collapse = "\n")
}

# Extract lines before the first id marker -----------------------------------
extract_preamble <- function(script_path) {
  lines <- readLines(script_path)
  first_id <- which(grepl("^\\s*# \\[", lines))[1]
  if (is.na(first_id) || first_id <= 1) return("")
  paste(lines[seq_len(first_id - 1)], collapse = "\n")
}

# LLM code generation for new steps ------------------------------------------
llm_generate_step <- function(node, style_context, chat) {
  prompt <- glue::glue(
    "You are writing a step in an R analysis script.
    
    The existing code style is:
    ```r
    {style_context}
    ```
    
    Write R code for the following step. Reference the style above:
    - ID: {node$id}
    - Action: {node$action}
    - Decision: {node$decision}
    - Justification: {node$justification}
    - Inputs: {paste(unlist(node$inputs), collapse = ', ')}
    - Outputs: {paste(unlist(node$outputs), collapse = ', ')}
    
    Return only the R code, no explanation, no markdown fences."
  )
  
  response <- chat$chat(prompt)
  
  response
}
